name: CI | Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t dorfnew/ai-api-sdxl:dev .
      - name: Run tests
        run: |
          docker run --rm -e HF_TOKEN=${{ secrets.HF_TOKEN }} dorfnew/ai-api-sdxl:dev python -c "import src.rp_handler; src.rp_handler.run_tests('{\"input\": {\"type\": \"image\", \"prompt\": \"a majestic steampunk dragon soaring through a cloudy sky, intricate clockwork details, golden hour lighting, highly detailed\", \"negative_prompt\": \"blurry, very low quality, deformed, ugly, text, watermark, signature,\", \"height\": 1024, \"width\": 1024, \"num_inference_steps\": 25, \"refiner_inference_steps\": 50, \"guidance_scale\": 7.5, \"strength\": 0.3, \"high_noise_frac\": 0.8, \"seed\": 1337, \"scheduler\": \"K_EULER\", \"num_images\": 1, \"image_url\": null}}')"