name: CI | Test Worker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  initialize_worker:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.extract_id.outputs.runpod_job_id }}
    steps:
      - name: Deploy Worker
        id: deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.runpod.io/v2/${{ vars.RUNNER_24GB }}/run"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.RUNPOD_API_KEY }}
          data: '{"input":{"github_pat": "${{ secrets.GH_PAT }}", "github_org":"${{ vars.GH_ORG }}"}}'
      - name: Extract Job ID
        id: extract_id
        run: |
          RESPONSE='${{ steps.deploy.outputs.response }}'
          if [ -z "$RESPONSE" ]; then
            echo "Error: No response from RunPod API"
            exit 1
          fi
          ID=$(echo "$RESPONSE" | jq -r '.id')
          if [ "$ID" = "null" ] || [ -z "$ID" ]; then
            echo "Error: Failed to extract RunPod job ID"
            exit 1
          fi
          echo "runpod_job_id=$ID" >> $GITHUB_OUTPUT

  run_tests:
    needs: initialize_worker
    runs-on: runpod
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11 & install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt
          apt-get install -y ffmpeg libsm6 libxext6
      - name: Execute Tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python src/rp_handler.py --test_input='{"input": {"type": "image", "prompt": "a majestic steampunk dragon soaring through a cloudy sky, intricate clockwork details, golden hour lighting, highly detailed", "steps": 25, "width": 1024, "height": 1024}}'

  terminate_worker:
    if: ${{ always() }}
    needs: initialize_worker
    runs-on: ubuntu-latest
    steps:
      - name: Shutdown Worker
        id: shutdown
        continue-on-error: true
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.runpod.io/v2/${{ vars.RUNNER_24GB }}/cancel/${{ needs.initialize_worker.outputs.id }}"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.RUNPOD_API_KEY }}
      - name: Check Shutdown Response
        run: |
          RESPONSE='${{ steps.shutdown.outputs.response }}'
          STATUS='${{ steps.shutdown.outputs.status }}'
          if [ "$STATUS" != "200" ]; then
            echo "Warning: Failed to terminate RunPod worker (Status: $STATUS, Response: $RESPONSE)"
          else
            echo "RunPod worker terminated successfully"
          fi
