name: Deploy to RunPod Pod

on:
  workflow_dispatch:
    inputs:
      pod_id:
        description: 'RunPod POD_ID (e.g., hpvdausak8xb00) obtained from the console after creating the pod'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to RunPod Pod
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          POD_ID: ${{ github.event.inputs.pod_id }}
        run: |
          chmod +x deploy/deploy_pod.sh
          ./deploy/deploy_pod.sh
