name: Unified Docker Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify files
        run: |
          ls -la
          [ -f sources.list ] || { echo "sources.list missing"; exit 1; }
          [ -f Dockerfile.unified ] || { echo "Dockerfile.unified missing"; exit 1; }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up environment variables
        run: |
          echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV

      - name: Build and push Unified Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.unified
          platforms: linux/amd64
          push: true
          tags: dorfnew/unified-ai-suite:latest
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}